import type { Metadata } from "next";
import "./globals.css";
import { inter } from "../common/styles";
import { ThemeProvider } from "../common/stores/ThemeProvider";
import Layout from "../common/components/layouts";



export const metadata: Metadata = {
  title: "Aditya Bintara | Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={inter.className}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <Layout>
            {children}
          </Layout>
        </ThemeProvider>
      </body>
    </html>
  );
}
